DeveloperAcademy-POSTECH/2024-MacC-M13-3I

PennyPack.xcodeproj/project.pbxproj
PennyPack.xcodeproj/xcshareddata/xcschemes/PennyPack.xcscheme
PennyPack/CameraService.swift
PennyPack/Source/App/PennyPackApp.swift
PennyPack/Source/View/ScanView.swift

* 카메라에서 사진을 찍으면 글자 스캔까지 완료
*
*
---

[Feat/#4] 스캔뷰

---

PennyPack/Source/View/CartView.swift

[Feat] 카트뷰

---

PennyPack/Assets.xcassets/Color/Contents.json
PennyPack/Assets.xcassets/Color/RBackgroundGray.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RBlack.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RCameraBlack.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RLightGray.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RMainBlue.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RPink.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RRed.colorset/Contents.json
PennyPack/Assets.xcassets/Color/RStrokeGray.colorset/Contents.json

[Setting] Color setting

---

APIKey.xcconfig
PennyPack.xcodeproj/project.pbxproj
PennyPack/Info.plist
PennyPack/Network/Const.swift
PennyPack/Source/View/MainView.swift
PennyPack/Source/View/ScanView.swift
PennyPack/ViewModel/CurrencyService.swift

* 나라 선택
* 환율 값 Double
* 영업일 반영
*
---

[Feat] #8 - 환율 기능 수정

---

PennyPack.xcodeproj/project.pbxproj
PennyPack/Source/App/PennyPackApp.swift
PennyPack/Source/View/CalendarView.swift
PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ContentView.swift
PennyPack/Source/View/ReceiptView.swift
PennyPack/Source/View/ResultView.swift
PennyPack/Source/View/ScanView.swift
PennyPack/ViewModel/DocumentScannerView.swift
PennyPack/ViewModel/ListModel.swift
PennyPack/ViewModel/TranslationSerivce.swift

*ScanView에서 번역된 정보 CartView의 리스트로 전송
*
*
---

[Feat]-list 생성

---

PennyPack.xcodeproj/project.pbxproj
PennyPack/Source/View/Regex.swift
PennyPack/ViewModel/OtherFuncs.swift

[Feat] 정규표현식 함수 테스트

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ContentView.swift
PennyPack/Source/View/MainView.swift
PennyPack/Source/View/ResultView.swift
PennyPack/Source/View/ScanView.swift
PennyPack/ViewModel/ListModel.swift
PennyPack/ViewModel/ShoppingListModel.swift
PennyPack/ViewModel/TranslationSerivce.swift

* UserDefaults 저장 & 불러오기
*
*
---

[Feat] - 리스트들 UserDefaults로 저장

---

PennyPack/Source/View/Regex.swift
PennyPack/Source/View/ScanView.swift
PennyPack/ViewModel/OtherFuncs.swift

* 정규표현식 가격 뽑아내기 -> ocr 낮은 인식률로 뽑아낼 수 없는 가격들이 있음. 약 50%의 예외 상황에서 개선법 찾아야 함
*
*
---

[Feat] #25 정규표현식 가격 뽑아내기

---

PennyPack/Source/View/Regex.swift

[Feat] #29 정규표현식 수정 미완

---

PennyPack/Source/View/CalendarView.swift
PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ContentView.swift
PennyPack/Source/View/MainView.swift
PennyPack/Source/View/ReceiptView.swift
PennyPack/Source/View/ResultView.swift
PennyPack/Source/ViewSource/DropdownListView.swift
PennyPack/Source/ViewSource/ListView.swift
PennyPack/Source/ViewSource/ResultModalView.swift
PennyPack/Source/ViewSource/TestView.swift
PennyPack/ViewModel/ListModel.swift
PennyPack/ViewModel/ShoppingListModel.swift

* resultView, receiptView 분리
* calendarView에서 선택하면 맞는 기록 보여주기
*
---

[Feat] - 기록들 저장& 보여주기 전체 정리 완료.

---

PennyPack/Source/View/Regex.swift
PennyPack/Source/View/ScanView.swift
PennyPack/Ubea/TestView.swift

* 상품명 가져오기: 프랑스어 문자 4자 이상
*
*
---

[Feat] 정규표현식 상품명

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/ViewSource/ListView.swift
PennyPack/ViewModel/ListModel.swift
PennyPack/ViewModel/ShoppingListModel.swift

[Feat] - 리스트 삭제기능 추가

---

PennyPack/Font/FontExtension.swift
PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ContentView.swift
PennyPack/Source/View/MainView.swift
PennyPack/Source/View/ResultView.swift
PennyPack/Source/ViewSource/DropdownListView.swift
PennyPack/Source/ViewSource/ResultModalView.swift
PennyPack/ViewModel/ShoppingListModel.swift

[Design] ui 1차 공사 완.

---

PennyPack/Source/View/CalendarView.swift

[Feat]캘린더 커스텀

---

PennyPack/Source/View/CalendarView.swift

[Feat]캘린더 커스텀 수정

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ContentView.swift
PennyPack/ViewModel/ShoppingListModel.swift

* cartView에 전 기록들 남아있는거 수정완료.
*
*
---

[Feat] 최종가격 맞게 수정.

---

PennyPack.xcodeproj/project.pbxproj
PennyPack/Source/View/ScanView.swift
PennyPack/ViewModel/CameraModel.swift
PennyPack/ViewModel/CameraPreview.swift
PennyPack/ViewModel/Scan2Service.swift

* 카메라 새로 구현 
* ocr 아직 미구현
*
---

[Feat]#41 카메라 새로 구현

---

PennyPack/Source/View/CartView.swift
PennyPack/ViewModel/CurrencyService.swift
PennyPack/ViewModel/ListModel.swift
PennyPack/ViewModel/ShoppingListModel.swift

[Feat] 앱 중간점검

---

PennyPack/Source/View/CartView.swift

* scanView에 받아오는 ViewModel 수정
*
*
---

[Fix] #55 - 머지 후 이슈난거 수정함.

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/ViewSource/ListView.swift
PennyPack/Source/ViewSource/ResultModalView.swift
PennyPack/ViewModel/ShoppingListModel.swift

* CartView 텍스트 추가버튼 누르면 리스트 항목 추가
*
*
---

[Feat] 텍스트버튼 누르면 항목 추가

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ContentView.swift
PennyPack/Source/View/Regex.swift
PennyPack/Source/View/ScanView.swift
PennyPack/Ubea/TestView.swift
PennyPack/ViewModel/DocumentScannerView.swift
PennyPack/ViewModel/ShoppingListModel.swift
PennyPack/ViewModel/TranslationSerivce.swift

Feat/#63 전체적인 코드 수정

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/View/Regex.swift
PennyPack/Source/ViewSource/ResultModalView.swift
PennyPack/ViewModel/ShoppingListModel.swift

* 스캔뷰 카메라 데이터 연결, 유로 더블 수정
*
*
---

[Feat] 스캔뷰 카메라 데이터 연결, 유로 더블 수정

---

PennyPack/Source/View/CalendarView.swift
PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ReceiptView.swift
PennyPack/ViewModel/OtherFuncs.swift
PennyPack/ViewModel/ShoppingListModel.swift

[Fix] - 출시로 가기위한 수정에수정에 수정

---

PennyPack/Source/View/CartView.swift

* frcPrice 없앤 변수인데 전 머지에서 못없애서 고생해떠요 ㅠㅠ
*
*
---

[Fix] - 이친구가 중괄호 구라쳐서 윈터랑 씨씨랑 눈빠질뻔;;

---

PennyPack.xcodeproj/project.pbxproj
PennyPack/Source/View/ScanView.swift
PennyPack/Ubea/TestView.swift
PennyPack/ViewModel/DocumentScannerView.swift
PennyPack/ViewModel/ScannerRetakeView.swift

* 리테이크 구현
* DocumentScannerView -> ScannerRetakeView로 이동
*
---

[Feat]#79 스캔뷰 대공사

---

PennyPack/Source/View/Regex.swift
PennyPack/Source/View/ScanView.swift
PennyPack/Ubea/TestView.swift
PennyPack/ViewModel/ScannerRetakeView.swift

* 스캔뷰 코드 수정
* 
*
---
- 수정 및 저장 버튼 값 없을 때 비활성화
- 이미지 띄우는 코드 수정
- 이미지 크기 조정

[Feat] 스캔뷰 코드 수정

---

PennyPack/Source/View/Regex.swift
PennyPack/Source/View/ScanView.swift

[Fix] - 되돌아가즈아

---

PennyPack.xcodeproj/project.pbxproj
PennyPack/Source/View/CartView.swift
PennyPack/Source/ViewSource/CustomAlertView.swift
PennyPack/Source/ViewSource/Regex.swift

*CustomAlertView 생성 & 커스텀 완료.
*
*
---
- [ korUnitItem이 이상함 ] To-Do Item

[Fix] - CustomAlertView 생성 & 커스텀 완료.

---

PennyPack/Source/View/CartView.swift
PennyPack/Source/View/ScanView.swift
PennyPack/Source/ViewSource/CustomAlertView.swift
PennyPack/Source/ViewSource/Regex.swift

[Fix]#100 머지 오류난 코드 수정

---

PennyPack.xcodeproj/project.pbxproj
PennyPack.xcodeproj/xcshareddata/xcschemes/PennyPack.xcscheme
PennyPack/ViewModel/TranslationSerivce.swift

* 최종 1차 심사본
* APIkey 수정 & BundleID 수정
*
---

[HotFix] - APIkey 수정 & BundleID 수정

---

PennyPack.xcodeproj/project.pbxproj

[Fix] iPad 삭제

---

PennyPack.xcodeproj/project.pbxproj

[Fix]#108 - 카메라권한 문구 수정
